### ISSUE TITLE
Error While Running index.js

### ISSUE THREAD

**Issue by samlasar** [swissmanu/ucwajs#1]
## After installing and doing appropriate changes by creating config.json with valid username and password, I'm getting below error while running index.js

C:\Users\lsamuel\workspace\git\ucwajs>node index.js
C:\Users\lsamuel\workspace\git\ucwajs\lib\autoDiscover.js:20
                        if(res.ok) {
                              ^
TypeError: Cannot read property 'ok' of undefined
##     at C:\Users\lsamuel\workspace\git\ucwajs\lib\autoDiscover.js:20:10

Equivalent code in autoDiscover.js

---

request.end(function(err, res) {
if(res.ok) {
    debug('Got autodiscover');
    deferred.resolve(res.body);
} else {
    debug('Got error from API');
    deferred.reject(err);
}
## });

Help Please...

**Comment by swissmanu** [comment]
as stated in the [README.md](https://github.com/swissmanu/ucwajs/blob/master/README.md), this is an experimental project and I do not provide any support for it.

however, you can try to enable the debug traces (see readme too) to make tracking down your problem easier.
